### ISSUE TITLE
not work for outook2013

### ISSUE THREAD

**Issue by asmc** [mwrlabs/XRulez#4]

**Comment by rookuu** [comment]
Odd, my test cases were on 2013.

What is the error it's giving you?
What version of exchange are you using?

**Comment by mubix** [comment]
I have the same issue, this is what I get:

<img width="658" alt="xrulez_fail" src="https://cloud.githubusercontent.com/assets/679319/19118973/3294fe3a-8aec-11e6-8aa1-e9b6da038dfc.png">

Then it shows this after clicking continue:

```
[ERROR] MAPI failed to initialize.

Possible Causes:
* Outlook isn't installed.
* You're using 64bit XRulez on a 32bit system (or vise versa).

A dialog box has been shown to the user! (Oops)

```

**Comment by Meatballs1** [comment]
<3 @mubix

**Comment by rookuu** [comment]
That error is usually when you're trying to run 64bit XRulez with a 32bit install of Outlook (or the other-way around).

Can you confirm that the version of Outlook running on the target machine is also 64bit?

**Comment by mubix** [comment]
I attempted both the 32bit `XRulez86.exe` and the 64bit `XRules64.exe`
- OS is Windows 10 x64
- Outlook si 2013 x86

**Comment by rookuu** [comment]
Sorry about the delay on this. I'm going to investigate this further at the weekend.
