### ISSUE TITLE
cann't get rule

### ISSUE THREAD

**Issue by simiden** [mwrlabs/XRulez#5]
This is the result of run the xrulez ,it seems create the rule,both the outlook2010 32bit and the 2013 bit. os windows7 x64 .but cann't see the rule in the outlook. what is the problem of this. is the problem of the encoded and the different  language version.
/ /^\ | |\ \ | |_| || ||  __/ / /
 \/   \/_| _| __,_||_| ___|/___|
- Exchange Rule Injector

[XRulez] Adding new rule

With Parameters:
profile = Outlook
name = takeme
trigger = pig
payload = c:\windows\notepad.exe

[Info] It looks like Outlook is running, continuing...
[Info] Opened folder: '???'
[Info] A new message in the associated message table has been created
[Info] Message has been populated with properties and synced with Exchange.

C:\test\src>

**Comment by rookuu** [comment]
> is the problem of the encoded and the different language version.

Possibly, what language are you using?

> [Info] Opened folder: '???'

Is this line the identical output of XRulez?

**Comment by simiden** [comment]
the os is english,and the outlook is Korean, the [Info] Opened folder: '???'  is the identical output of Xrulez. the issue can't upload the pic.

if the xrulez cann't open the folder,it will echo a error, the problem is all the execute success,but it failed create the rule.
is these a solution for all language version.
